<template>
  <DocsContainer>
    <DocsButtonPrimary/>
    <DocsButtonWithIcon/>
    <DocsButtonOutlined/>
    <DocsButtonDisabled/>
    <DocsButtonRing/>
    <DocsButtonBlock/>
  </DocsContainer>
</template>