// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/docs/Buttons/Block.vue')['default']
    Disabled: typeof import('./src/components/docs/Buttons/Disabled.vue')['default']
    DocsAlertAltSuccess: typeof import('./src/docs/Alert/DocsAlertAltSuccess.vue')['default']
    'DocsAlertAltSuccess copy': typeof import('./src/docs/Alert/DocsAlertAltSuccess copy.vue')['default']
    DocsAlertSuccess: typeof import('./src/docs/Alert/DocsAlertSuccess.vue')['default']
    DocsButtonBlock: typeof import('./src/docs/Button/DocsButtonBlock.vue')['default']
    DocsButtonDisabled: typeof import('./src/docs/Button/DocsButtonDisabled.vue')['default']
    DocsButtonOutlined: typeof import('./src/docs/Button/DocsButtonOutlined.vue')['default']
    DocsButtonPrimary: typeof import('./src/docs/Button/DocsButtonPrimary.vue')['default']
    DocsButtonRing: typeof import('./src/docs/Button/DocsButtonRing.vue')['default']
    DocsButtonWithIcon: typeof import('./src/docs/Button/DocsButtonWithIcon.vue')['default']
    DocsContainer: typeof import('./src/components/DocsContainer.vue')['default']
    DocsListItem: typeof import('./src/components/DocsListItem.vue')['default']
    DocsNavbarSimple: typeof import('./src/docs/Navbar/DocsNavbarSimple.vue')['default']
    DocsProgressSimple: typeof import('./src/docs/Progress/DocsProgressSimple.vue')['default']
    DocsProgressWithLabel: typeof import('./src/docs/Progress/DocsProgressWithLabel.vue')['default']
    DocumentationContainer: typeof import('./src/components/docs/DocumentationContainer.vue')['default']
    Footer: typeof import('./src/layouts/Footer.vue')['default']
    ListItem: typeof import('./src/components/Sidebar/ListItem.vue')['default']
    Navbar: typeof import('./src/layouts/Navbar.vue')['default']
    Outlined: typeof import('./src/components/docs/Buttons/Outlined.vue')['default']
    PreviewHeader: typeof import('./src/components/Preview/PreviewHeader.vue')['default']
    PreviewRightButton: typeof import('./src/components/Preview/PreviewRightButton.vue')['default']
    PreviewTrayButton: typeof import('./src/components/Preview/PreviewTrayButton.vue')['default']
    Primary: typeof import('./src/components/docs/Buttons/Primary.vue')['default']
    Ring: typeof import('./src/components/docs/Buttons/Ring.vue')['default']
    Sidebar: typeof import('./src/layouts/Sidebar.vue')['default']
    SidebarListItem: typeof import('./src/components/Sidebar/SidebarListItem.vue')['default']
    Simple: typeof import('./src/components/docs/Progress/Simple.vue')['default']
    SimplePreview: typeof import('./src/components/Preview/SimplePreview.vue')['default']
    WithIcon: typeof import('./src/components/docs/Buttons/WithIcon.vue')['default']
    WithLabel: typeof import('./src/components/docs/Progress/WithLabel.vue')['default']
  }
}

export { }
